### PR TITLE
php7 compatibility.

### LINKED ISSUE #1: PHP 7+ Compatibility
```
FILE: /wp-content/plugins/exchange-addon-membership/vendor/ironbound/wp-notifications/src/Strategy/Null.php
------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------------------------------------
15 | ERROR | 'null' is a reserved keyword as of PHP version 7.0 and cannot be used to name a class, interface or trait or as part of a namespace (T_CLASS)
------------------------------------------------------------------------------------------------------------------------------------------------------------ 
```

### PR DESCRIPTION
**Pull request by kjohnson**
The class name of the `Null` strategy is throwing an error in php7+, as `null` is a reserved keyword and cannot be used in  class or namespace.

Closes #1.

**Changes**
- Renamed `Null` to `Null_Mail`, matching the naming convention of `WP_Mail` and `Null_Listener`.
- Updated references Null Strategy references.
- Autoload a class alias for `Null` to `Null_Mail`. See: [Autoload Files](https://getcomposer.org/doc/04-schema.md#files)

### CODE REVIEW

**Comment by TimothyBJacobs** [comment]
:+1: This will need a `class_alias` to not break existing installs. I believe it’d have to be added to a new file that is always loaded by composer as opposed to adding it to the class definition file as that won’t be autoloaded when using the old class name.

**Comment by kjohnson** [comment]
@TimothyBJacobs I'm back at it.

I added a `class_alias` using Composer's Autoload File schema.

**Comment by kjohnson** [comment]
@TimothyBJacobs looks like the alias needs to be loaded conditionally by PHP Version.
The alias throws an error in php7+.

Also, I added a test for the Null strategy alias.

**Comment by TimothyBJacobs** [comment]
Looks good to me, thanks for the fix!

As an aside, I'd try and move off this when you can. It isn't really great performance wise, or really in any way anymore.

**Comment by kjohnson** [comment]
@TimothyBJacobs ok - thanks for the heads up!

**Pull request merged**
